matrix:
    include:
        - language: python
          cache: pip
          python: "3.8.1"
          install:
            - pip install pipenv --upgrade
            - pipenv sync -d
          before_script:
            - python --version
          script:
            - black --check app/
            - flake8
            - pytest
            - coverage erase
            - coverage run --source="." pytest && coverage html
          after_success:
            - codecov

        - language: node.js
          node_js: "12.18.3"

          install:
            - npm install newman

          before_script:
            - node --version
            - npm --version
            - node_modules/.bin/newman --version

          script:
            - node_modules/.bin/newman run postman/Evolux.postman_collection.json -e postman/env_evolux.postman_environment.json
