version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /c/users:/users
    ports:
      - "5000:5000"
    environment:
      - FLASK_CONFIG=development
      - FLASK_APP=run.py