version: '3.7'

services:

  users:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - FLASK_CONFIG=development
      - FLASK_APP=run.py